import Contacts from '../model/contacts.js';
import { checkEmail, checkNumber } from '../utils/validator.js';
import config from '../config.js';
import nodemailer from 'nodemailer'; 
import moment from 'moment';

let mailTransporter = nodemailer.createTransport({ 
    service: 'gmail', 
    auth: config.auth
});

//add user query
export const AddQuery = async(req,res) => {
    // console.log(req.body)
    let cur_date = moment(new Date(Date.now())).format('YYYY-MM-DD HH:mm:ss');

    try{

        const IsValid = checkEmail(req.body.userEmail);
        if(!IsValid){
            res.send("Invalid Email")
        }

        const IsValidPhone = checkNumber(req.body.phone);
        if(!IsValidPhone){
            res.send("Invalid phone number")
        }

        let data = {
            date : req.body.date ? req.body.date : cur_date,
            userName : req.body.userName,
            userEmail : req.body.userEmail,
            phone : req.body.phone,
            comment : req.body.comment             
        }
        let mailDetails = { 
            from: config.auth.user, 
            to: data.userEmail, 
            subject: 'Customer service - Amazed.in', 
            html: `
                <p>Hi ${data.userName},</p>
                    <p>Thank you for contacting us.</p>
                    <p>Will contact you soon.</p>
                <p>Regards,</p>
                <p>Customer Service Team- Amazed</p> 
                
                <pre>This is an autogenerated reply for your message ...
                ${data.comment}
                </pre>
            `
        };
        const response = await Contacts.create(data)
            res.status(201).send({"success":"Successfully added the comment"})
            mailTransporter.sendMail(mailDetails, function(err, data) { 
                if(err) { 
                    console.log('Error Occurs'); 
                } else { 
                    console.log('Email sent successfully'); 
                } 
            }); 
        }

        catch(error){
            res.status(409).send({"err":error.message})
        }
};

//get all contact us data

export const getContactUs = async (req, res) => {
    
    try {

        if(!req.session.user && req.session.user.role !=='Admin') {
            return res.status(400).send('No Session Found! Please Login Again')
        }

        const data = await Contacts.find({});
        return res.status(200).send(data);
    }
    catch(error) {
        return res.status(409).send({"err": error.message});
    }
} 

//update contact us info
export const updateContact = async (req, res) => {
    try {

        if(!req.session.user && req.session.user.role !=='Admin') {
            return res.status(400).send('No Session Found! Please Login Again')
        }

        const _id = req.params.id
        const updaterequired = await Contacts.findByIdAndUpdate(_id, req.body.contact);

        res.status(204).send({"sucess":"Data is updated successfully"});
    }

    catch (error) {
        res.status(404).send({"err":error.message})
    }
};